name: Develop Push

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: registry.us-east-1.aliyuncs.com
          username: ${{ secrets.CR_GITHUB_ACTION_USERNAME }}
          password: ${{ secrets.CR_GITHUB_ACTION_PASSWORD }}

      - run: |
          docker build . -t registry.us-east-1.aliyuncs.com/github-action/pandoc:develop
          docker push registry.us-east-1.aliyuncs.com/github-action/pandoc:develop
